name: scan docker image

on: 
  push:
    branches: main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup docker
        uses: docker/setup-buildx-action@v2

      - name: build docker image
        run:  |
          docker build -t my-app:latest .

      - name: scan with trivy
        uses: aquasecurity/trivy-action@master
      
      - name: Deploy or next steps
        run: echo "Scan completed. Proceeding to next step..."
