name: scan docker image

on: 
  push:
    branches: main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup docker
        uses: docker/setup-buildx-action@v2

      - name: build docker image
        run:  |
          docker build -t my-app:latest .

      - name: scan with trivy
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: 'my-app:latest'
          severity: 'HIGH, CRITICAL'
          ignore-unfixed: true
          exit-code: '0'
          format: 'table'

      - name: Deploy or next steps
        if: success()
        run: echo "no critical or high"

